echo Resolving IP for 'raspberrypi.local'...
RPI_IP=$(avahi-resolve --name raspberrypi.local | python -c 'import sys; print(str(sys.stdin.read())[18:])')
echo Opening $RPI_IP:8080 in your browser...
python3 -m webbrowser $RPI_IP:8080