ASTROPI_PORT = 2999
ASTROPI_TRANSFER_PORT = 3000
ASTROPI_PREVIEW_PORT = 3001
DISCONNECTED = 0
DISCONNECTED_TEXT = "<p style='color: red;'>DISCONNECTED</p>"
CONNECTED = 1
CONNECTED_TEXT = "<p style='color: green;'>CONNECTED</p>"
CONNECTING = 2
CONNECTING_TEXT = "<p style='color: yellow;'>CONNECTING</p>"
UNKNOWN = 3
UNKNOWN_TEXT = "<p style='color: blue;'>UNKNOWN</p>"
SYSTEM_UPDATE = 4
PULL_UPDATES = 5
AUTO = -1
INFINITY = -2
FILE_SEPARATOR = "<NEWFILE>"
JSON_SEPARATOR = "<NEWJSON>"